SRE - 822
bukalapak/redis-rb pull request #1
Opened 2018-07-18 09:43 UTC by galuhest

2018-07-19 05:33 UTC, indrasaputra requested changes

2018-07-19 05:33 UTC, indrasaputra commented on grep
> +invalid option: -e
file ini buat apa ya?

2018-07-19 05:33 UTC, indrasaputra commented on test/circuit_breaker_test.rb
> +require_relative "helper"
pake petik 1 aja
useful links
- https://github.com/rubocop-hq/ruby-style-guide
- https://github.com/rubocop-hq/rails-style-guide

2018-07-19 05:33 UTC, indrasaputra commented on test/circuit_breaker_test.rb
> +    result = r.call("PING")
kalo string nya ga diinterpolasi, pake petik 1

2018-07-19 05:33 UTC, indrasaputra commented on test/circuit_breaker_test.rb
> +    assert_equal result, "PONG"
ini juga. yg lain juga ya

2018-07-19 05:33 UTC, indrasaputra commented on test/circuit_breaker_test.rb
> +  	(0..90).each do |i|
indentasi nya dibenerin ya

2018-07-19 05:33 UTC, indrasaputra commented on test/helper.rb
> +end
kasi newline setelah ini

2018-07-19 05:33 UTC, indrasaputra commented on test/helper.rb
> +  def fails
ini pake 2 spasi, tapi yg di atas tadi kok pake 4 spasi ya?
diseragamkan aja

2018-07-19 05:33 UTC, indrasaputra commented on test/helper.rb
> +    end
kasi newline setelah ini

2018-07-19 05:55 UTC, galuhest commented on grep
> +invalid option: -e
eh, gak sengaja ngeprint grep ke file >.<

2018-07-19 06:21 UTC, IndraGunawan commented on test/circuit_breaker_test.rb
> +  	(0..90).each do |i|
sepertinya langsung tambahin file `.editorconfig` aja untuk bantuin

2018-07-19 06:31 UTC, galuhest commented on test/circuit_breaker_test.rb
> +  	(0..90).each do |i|
entah kenapa buat file ini doang sebagian tab gak jadi space

2018-07-19 07:28 UTC, indrasaputra commented on test/circuit_breaker_test.rb
> +  	(0..90).each do |i|
@davidchrisx monggo dibantu

2018-07-19 07:30 UTC, indrasaputra requested changes

2018-07-19 07:30 UTC, indrasaputra commented on test/circuit_breaker_test.rb
> +    end
indentasi

2018-07-19 07:30 UTC, indrasaputra commented on lib/redis/client.rb
> +    circuit_handler do |handler|
option2 di sini harusnya bisa configurable. kalau kayak gini jadi ga configurable karena udah hardcoded

2018-07-19 07:30 UTC, indrasaputra commented on test/helper.rb
> +      raise RedisError, "redis error"
petik satu kalo string nya ga terinterpolasi

2018-07-19 07:33 UTC, galuhest commented on lib/redis/client.rb
> +    circuit_handler do |handler|
maksudnya opsi dari timeout, threshold, gitu gitunya?

2018-07-19 07:37 UTC, indrasaputra commented on lib/redis/client.rb
> +    circuit_handler do |handler|
iya. jadi user bisa nentuin sendiri mau berapa timeout, threshold, dll

2018-07-19 11:57 UTC, indrasaputra commented
@davidchrisx jangan lupa direview ya

2018-07-25 05:54 UTC, indrasaputra requested changes

2018-07-25 05:54 UTC, indrasaputra commented on lib/redis/client.rb
> +      @metric = Prometheus::Client::Counter.new(:redis_circuit_breaker_trips_total, "Counter for the amount of circuit braker trips")
typo `circuit braker trips`

2018-07-25 06:13 UTC, indrasaputra approved these changes

2018-07-25 07:10 UTC, merged