[SRE-859] Tracing
bukalapak/redis-rb pull request #3
Opened 2018-08-08 12:39 UTC by galuhest

implement tracing capabilities to Redis-rb

2018-08-08 13:21 UTC, reza-putra requested changes

2018-08-08 13:21 UTC, reza-putra commented on lib/redis/client.rb
> +      parent = OpenTracing.scope_manager.active
saya lebih prefer pakai context sih, karena lebih jelas parent span nya. bisa samakan dengan mongo-gate https://github.com/bukalapak/mongo-gate/blob/e37a0439a947672089be0beb10fd94f42869f0cb/lib/mongo-gate.rb#L76

2018-08-09 04:05 UTC, galuhest commented on lib/redis/client.rb
> +      parent = OpenTracing.scope_manager.active
- Saya mikirnya karena span yang aktif dalam satu thread itu cuman bisa 1 jadinya ini harusnya cukup jelas
- Tujuan saya buat seperti ini juga maksudnya biar developer bisa menggunkan fitur tracing tanpa perlu memanggil wrapper terhadap fungsinya -- kalau dia sudah pakai tracer di aplikasi utamanya maka tracer di library ini otomatis jalan

2018-08-09 06:31 UTC, evo3cx commented on lib/redis/client.rb
> +      parent = OpenTracing.scope_manager.active
diruby sendiri memang tidak ada kemampuanuntuk concurent, tapi jika client menggunakan library yang memungkinkan concurrent ini bisa salah parent nya.

contoh lib: https://github.com/ruby-concurrency/concurrent-ruby

2018-08-09 06:37 UTC, galuhest commented on lib/redis/client.rb
> +      parent = OpenTracing.scope_manager.active
ah ya, noted.
kalau saya buat jadi saat user mau buat object redisnya yang dibutuhkan itu bukan apa driver tracingnya, tapi apa span/scope yang mau dijadikan parent gimana? kalau dia gak pasang itu baru redisnya buat span baru sendiri

2018-08-09 06:42 UTC, evo3cx commented on lib/redis/client.rb
> +      parent = OpenTracing.scope_manager.active
option context nya bisa di berikan default value `nil`, pada open tracing sendiri jika value `:child_of` =  `nil` dia akan menganggap itu satu tracing tanpa parent, detail implementasi nya bisa di lihat pada `mongo-gate`

2018-08-13 06:54 UTC, evo3cx commented on lib/redis.rb
> +    scope = tracing('echo')
`tracing` ini jadi ada di semua method operation ke redis yah, jika method `tracing` hanya di invoke pada `client.call` saja gmn yah? lebih simple aja sih sebenarnya.

2018-08-13 06:54 UTC, reza-putra approved these changes

2018-08-15 06:27 UTC, galuhest commented on lib/redis.rb
> +    scope = tracing('echo')
kalau kayak gitu jadinya ada function yang gak seluruh aktivitasnya didalem scope tracingnya mas, dan karena entry point di library ini ada banyak, jadinya saya pasang di tiap function yang bakal dipanggil user

2018-08-16 08:38 UTC, davidchrisx approved these changes

2018-08-16 08:44 UTC, merged